CuaHangTheThao/Controllers/DatHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CuaHangTheThao.Models;
namespace CuaHangTheThao.Controllers
{
    public class DatHangController : Controller
    {
        csdl_cuahangthethaoDataContext data = new csdl_cuahangthethaoDataContext();
        // GET: DatHang
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ThemMatHang(string msp, int iso_luong = 1)
        {
            GioHangmodel ghm = (GioHangmodel)Session["ghm"];
            if (ghm == null)
                ghm = new GioHangmodel();
            ghm.Them(msp, iso_luong);
            Session["ghm"] = ghm;


            return RedirectToAction("trangchu","Home");
        }


        public ActionResult XemGioHang()
        {
            GioHangmodel ghm = (GioHangmodel)Session["ghm"];
           

            return View(ghm);
        }

        public ActionResult SuaMatHang(string msp)
        {
            GioHangmodel ghm = (GioHangmodel)Session["ghm"];
            if (ghm == null)
                return RedirectToAction("XemGioHang");

            CartItem item = ghm.lst.FirstOrDefault(i => i.isan_pham_id == msp);
            if (item == null)
                return RedirectToAction("XemGioHang");

            return View(item);
        }
        [HttpPost]
        public ActionResult CapNhatSoLuong(string msp, int soLuong)
        {
            GioHangmodel ghm = (GioHangmodel)Session["ghm"];
            if (ghm != null)
            {
                var item = ghm.lst.FirstOrDefault(i => i.isan_pham_id == msp);
                if (item != null)
                {
                    item.iso_luong = soLuong;
                }
            }

            return Json(new { success = true });
        }
        [HttpPost]
        public ActionResult SuaGioHang(string msp, int quantityChange)
        {
            if (string.IsNullOrEmpty(msp))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid product ID");
            }

            GioHangmodel ghm = Session["ghm"] as GioHangmodel;
            if (ghm == null)
            {
                return RedirectToAction("XemGioHang");
            }

            CartItem item = ghm.lst.FirstOrDefault(i => i.isan_pham_id == msp);
            if (item == null)
            {
                return RedirectToAction("XemGioHang");
            }

            if (quantityChange < 0)
            {
                quantityChange = 0;
            }

            item.iso_luong = quantityChange;
            Session["ghm"] = ghm;

            return RedirectToAction("XemGioHang");
        }
        public ActionResult XoaMatHang(string msp)
        {
            GioHangmodel ghm = (GioHangmodel)Session["ghm"];
            if (ghm != null)
            {
                CartItem item = ghm.lst.FirstOrDefault(i => i.isan_pham_id == msp);
                if (item != null)
                {
                    ghm.lst.Remove(item);
                    Session["ghm"] = ghm;
                }
            }
            return RedirectToAction("XemGioHang");
        }
        public ActionResult XoaTatCaMatHang()
        {
            GioHangmodel ghm = (GioHangmodel)Session["ghm"];
            if (ghm != null)
            {
                // Xóa tất cả các mặt hàng trong giỏ hàng
                ghm.lst.Clear();
                Session["ghm"] = ghm;
            }

            // Chuyển hướng người dùng đến trang giỏ hàng
            return RedirectToAction("XemGioHang");
        }

        public ActionResult XacNhanDatHang()
        {
            if (Session["nd"] == null)
            {
                return RedirectToAction("DangNhap", "Home");
            }  

            GioHangmodel ghm = Session["ghm"] as GioHangmodel;
            if (ghm == null || !ghm.lst.Any())
            {
                return RedirectToAction("XemGioHang");
            }

            NguoiDung nd = Session["kh"] as NguoiDung;
            ViewBag.n = nd;

            return View(ghm);
        }
        [HttpPost]
        public ActionResult XLDatHang(FormCollection c)
        {   
            NguoiDung khach = Session["nd"] as NguoiDung;

            string donHangId = Guid.NewGuid().ToString();
            DonHang dh = new DonHang
            {
                don_hang_id= donHangId,
                nguoi_dung_id = khach.nguoi_dung_id,
                ngay_dat_hang = DateTime.Now,
            };
             

            data.DonHangs.InsertOnSubmit(dh);
            data.SubmitChanges();

            GioHangmodel ghm = Session["ghm"] as GioHangmodel;

            foreach (CartItem item in ghm.lst)
            {
                // Tạo giá trị cho chi_tiet_gio_hang_id, có thể sử dụng GUID hoặc một phương pháp sinh ID khác
                string chiTietDonHangId = Guid.NewGuid().ToString();

                ChiTietDonHang ctgh = new ChiTietDonHang
                {
                    chi_tiet_don_hang_id = chiTietDonHangId,
                    don_hang_id = donHangId,
                    san_pham_id = item.isan_pham_id,
                    so_luong = item.iso_luong,
                };

                data.ChiTietDonHangs.InsertOnSubmit(ctgh);
            }

            data.SubmitChanges();

            Session["ghm"] = null;

            ViewBag.tb = 1;


            return View();
        }
    }
}

CuaHangTheThao/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuaHangTheThao.Models;

namespace CuaHangTheThao.Controllers
{
    public class HomeController : Controller
    {
        csdl_cuahangthethaoDataContext data = new csdl_cuahangthethaoDataContext();
        // GET: Home
        public ActionResult Index()
        {
            
            return View();
        }
        public ActionResult trangchu(string danhMucId = null)
        {
            IQueryable<SanPham> spQuery = data.SanPhams;

            if (!string.IsNullOrEmpty(danhMucId))
            {
                spQuery = spQuery.Where(sp => sp.danh_muc_id == danhMucId);
            }

            List<SanPham> SP = spQuery.ToList();
            return View(SP);
        }
        public ActionResult DangNhap()
        {

            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection col)
        {
            var username = col["txtname"];
            var password = col["txtpass"];

            NguoiDung nd = data.NguoiDungs.FirstOrDefault(k => k.ten_dang_nhap == username && k.mat_khau == password);

            if (nd != null)
            {
                Session["nd"] = nd;
                return RedirectToAction("trangchu");
            }

            ViewBag.ErrorMessage = "Tên đăng nhập hoặc mật khẩu không đúng.";
            return View();
        }
        //Tạo nút thêm mới sản phẩm:
        //public ActionResult ThemMoi()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult ThemMoi(FormCollection collection ,SanPham sp)
        //{
        //    var ThemSanPham = collection["ten"];
        //    sp.ten = ThemSanPham;
        //    data.SanPhams.InsertOnSubmit(sp);
        //    data.SubmitChanges();
        //    return RedirectToAction("trangchu");
        //    return this.ThemMoi();

        //}
        public ActionResult DanhMucSanPham()
        {
            List<DanhMucSanPham> dmsp = data.DanhMucSanPhams.ToList();
            return PartialView(dmsp);
        }










        //public ActionResult DangKy()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult DangKy(FormCollection col)
        //{
        //    string tenDangNhap = col["txtname"];
        //    string matKhau = col["txtpass"];
        //    string email = col["txtemail"];
        //    string ho = col["txtho"];
        //    string ten = col["txtten"];
        //    string soDienThoai = col["txtphone"];
        //    string diaChi = col["txtaddress"];

        //    if (data.NguoiDungs.Any(nddk => nddk.ten_dang_nhap == tenDangNhap))
        //    {
        //        ViewBag.ErrorMessage = "Tên đăng nhập đã tồn tại.";
        //        return View();
        //    }

        //    NguoiDung nd = new NguoiDung
        //    {
        //        nguoi_dung_id = Guid.NewGuid().ToString(),
        //        ten_dang_nhap = tenDangNhap,
        //        mat_khau = matKhau,
        //        email = email,
        //        ho = ho,
        //        ten = ten,
        //        so_dien_thoai = soDienThoai,
        //        dia_chi = diaChi,
        //        ngay_dang_ky = DateTime.Now
        //    };

        //    data.NguoiDungs.InsertOnSubmit(nd);
        //    data.SubmitChanges();

        //    return RedirectToAction("DangNhap", "Home");
        //}

        //public ActionResult DangNhap()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult DangNhap(FormCollection col)
        //{
        //    string tenDangNhap = col["txtname"];
        //    string matKhau = col["txtpass"];

        //    NguoiDung nd = data.NguoiDungs.FirstOrDefault(k => k.ten_dang_nhap == tenDangNhap && k.mat_khau == matKhau);

        //    if (nd != null)
        //    {
        //        Session["nd"] = nd;
        //        return RedirectToAction("trangchu", "Home");
        //    }

        //    ViewBag.ErrorMessage = "Tên đăng nhập hoặc mật khẩu không đúng.";
        //    return View();
        //}
        public ActionResult Details(string id)
        {
            // Lấy thông tin sản phẩm theo id
            var sanPham = data.SanPhams.FirstOrDefault(sp => sp.san_pham_id == id);

            if (sanPham == null)
            {
                return HttpNotFound();
            }

            // Lấy danh mục sản phẩm cho sản phẩm này
            List<DanhMucSanPham> danhMuc = data.DanhMucSanPhams.ToList();

            // Truyền dữ liệu cho view
            ViewBag.DanhMuc = danhMuc;

            return View(sanPham);
        }


    }
}

CuaHangTheThao/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CuaHangTheThao/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CuaHangTheThao/Views/Home/DangNhap.cshtml
@{
    ViewBag.Title = "Đăng Nhập";
    Layout = "~/Views/Shared/layout_trangchu.cshtml";
}

<div class="d-flex justify-content-center">
    <div class="box">
        <h2>Đăng Nhập</h2>
        @using (Html.BeginForm("DangNhap", "Home", FormMethod.Post))
        {
            <div class="form-group">
                @Html.Label("Tên đăng nhập")
                @Html.TextBox("txtname", null, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.Label("Mật khẩu")
                @Html.Password("txtpass", null, new { @class = "form-control" })
            </div>
            <button type="submit" class="btn btn-primary">Đăng Nhập</button>
        }
        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger mt-2">@ViewBag.ErrorMessage</div>
        }
    </div>
</div>

CuaHangTheThao/Views/Home/DanhMucSanPham.cshtml
@using CuaHangTheThao.Models;
@model List<DanhMucSanPham>
@*@{
    ViewBag.Title = "DanhMucSanPham";
    Layout = "~/Views/Shared/layout_trangchu.cshtml";
}

<h2>DanhMucSanPham</h2>*@
<ul class="nav flex-column">
    <li class="nav-item" style="background-color:red">
        DANH MỤC SẢN PHẨM
    </li>
    @{ foreach (DanhMucSanPham dmsp in Model)
                    {
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("trangchu", "Home", new { danhMucId = dmsp.danh_muc_id })">@dmsp.ten</a>
        </li> } }
</ul>

CuaHangTheThao/Views/Home/Details.cshtml
@using CuaHangTheThao.Models;
@model CuaHangTheThao.Models.SanPham

@{
    ViewBag.Title = "Chi Tiết Sản Phẩm";
    Layout = "~/Views/Shared/layout_trangchu.cshtml";
    var danhMuc = ViewBag.DanhMuc as List<DanhMucSanPham>;
    <link href="~/Controllers/bootstrap/css/Details.css" rel="stylesheet" />
}

<!-- Link to the custom CSS file -->
<link rel="stylesheet" href="~/Content/CSS/product-details.css" />

<h2 class="product-title">Chi Tiết Sản Phẩm</h2>
<div class="product-details-container">
    <div class="row">
        <div class="col-md-4">
            <img src="@Url.Content("~/Content/Images/" + Model.hinh_anh_url)" alt="Product image" class="product-image" />
        </div>
        <div class="col-md-8">
            <div class="product-info">
                <h4 class="product-name">@Html.DisplayFor(model => model.ten)</h4>
                <label class="label-text">Mô Tả</label>
                <div class="description-text">@Html.DisplayFor(model => model.mo_ta)</div>
                <label class="label-text">Giá Bán</label>
                <div class="price-text">@String.Format("{0:###,### VND}", Model.gia)</div>
                <label class="label-text">Số Lượng</label>
                <div class="quantity-selector">
                    <button class="btn-decrease" onclick="updateQuantity(-1)">-</button>
                    <input type="text" id="quantity" class="quantity-input" value="1" readonly />
                    <button class="btn-increase" onclick="updateQuantity(1)">+</button>
                </div>
                <div class="category-list">
                    <p>Danh Mục:</p>
                    <ul>
                        @if (danhMuc != null)
                        {
                            foreach (var dm in danhMuc.Where(d => d.danh_muc_id == Model.danh_muc_id))
                            {
                                <li>@dm.ten</li>
                            }
                        }
                    </ul>
                </div>
                <a href="@Url.Action("ThemMatHang", "DatHang", new { msp = Model.san_pham_id })" class="btn-add-to-cart">Thêm Vào Giỏ Hàng</a>
            </div>
        </div>
    </div>
</div>

<script>
    function updateQuantity(change) {
        var quantityInput = document.getElementById('quantity');
        var currentQuantity = parseInt(quantityInput.value);
        var newQuantity = currentQuantity + change;
        if (newQuantity > 0) {
            quantityInput.value = newQuantity;
        }
    }
</script>

CuaHangTheThao/Views/Home/ThemMoi.cshtml
@model CuaHangTheThao.Models.SanPham

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Shared/layout_trangchu.cshtml";
}

<h2>ThemMoi</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mo_ta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mo_ta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mo_ta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.danh_muc_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.danh_muc_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.danh_muc_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.thuong_hieu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.thuong_hieu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.thuong_hieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.so_luong_ton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.so_luong_ton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.so_luong_ton, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hinh_anh_url, "Hình Ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="hinh_anh_url" class="form-control" />
                @Html.ValidationMessageFor(model => model.hinh_anh_url, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ngay_tao, "Ngày Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ngay_tao, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(model => model.ngay_tao, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "trangchu")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CuaHangTheThao/Views/Home/trangchu.cshtml
@using CuaHangTheThao.Models;
@model List<SanPham>

@{
    ViewBag.Title = "trangchu";
    Layout = "~/Views/Shared/layout_trangchu.cshtml";
}
<div class="row">
    @foreach (var sp in Model)
    {
        <div class="col-md-4 text-center mt-4 mb-4">
            <img src="/Content/Images/@sp.hinh_anh_url" class="w-100" alt="@sp.ten" />
            <p style="height:40px;">@sp.ten</p>
            <p>@String.Format("{0:###,### VND}", sp.gia)</p>
            <div class="card-body">
                
                @Html.ActionLink("Chi tiết", "Details", "Home", new { id = sp.san_pham_id }, new { @class = "btn btn-warning" })
                <a href="/DatHang/ThemMatHang/?msp=@sp.san_pham_id">
                    Chọn Mua
                </a>
            </div>
        </div>
    }
</div>